apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstore-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: bookstore-pv
  resources:
    requests:
      storage: 500Mi
